[package]
name = "dll_proxy"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
windows = { version = "0.61.3", features = ["Win32_System_SystemServices", "Win32_UI_WindowsAndMessaging"] }

payload = { path = "payload" }

[features]
debug = []
